// <auto-generated />
namespace FoodHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changes_meal_restaurant_model_keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_meal_restaurant_model_keys));
        
        string IMigrationMetadata.Id
        {
            get { return "202404061321096_changes_meal_restaurant_model_keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
