// <auto-generated />
namespace FoodHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class foodhub2init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foodhub2init));
        
        string IMigrationMetadata.Id
        {
            get { return "202404061203474_foodhub2-init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
